class Solution {
public:
    char findTheDifference(string s, string t) {
        map<char, int> count;
        for (char ch : s) count[ch] ++;

        for (char ch : t) {
            if (count[ch] == 0) return ch;
            count[ch] --;
        }
        return ' ';
    }
};


class Solution {
public:
    char findTheDifference(string s, string t) {
        int count[26] = {0};
        for (char c : s) count[c - 'a'] ++;
        for (char c : t) count[c - 'a'] --;
        for (int i = 0; i < 26; i ++) {
            if (count[i] == -1) return 'a' + i;
        }
        return ' ';
    }
};

/*
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.
*/
